---
title: "Model Specification"
author: "Steven Litvack-Winkler"
date: "5/1/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=8, fig.height=5) 

library(TSA)
library(readr)
```

## Importing/Processing Data

```{r}
data <- read_csv("sales_revenue_clean.csv")
```
## Custom functions

#### Plot function
```{r}
plot_months <- function(series,  mainLab = "title") {
  Month=c('J','F','M','A','M','J','J','A','S','O','N','D')
  
  plot(series, main = mainLab)
  points(series,pch=Month)
}
```

#### Series diagnostics
```{r}
stationary_test <- function(series){
  acf(series)
  pacf(series)
  print(runs(series))
  print(shapiro.test(series))
}
```

```{r}
totalRev <- ts(data$Tot_Revenue,start=c(1990,1),frequency=12)
plot_months(totalRev)
```

```{r}
totalRev2 = window(totalRev, start = c(2008, 1))
plot_months(totalRev2)
plot_months(diff(diff(totalRev2, k = 12), k = 12))
eacf(totalRev2)
eacf(diff(totalRev2, k = 12))
```


```{r}
totalMA = filter(totalRev,rep(1,13)/13,sides=2) # 1 year MA
plot(cbind(totalMA),plot.type='single',col=4:1,lwd=2, ylab="flow", main = "Total MA" )
lines(totalRev)
```

```{r}
stationary_test(totalRev)
```

```{r}
Time = time(totalRev)
totalRev_LM = lm(totalRev ~ Time)
summary(totalRev_LM)
```

```{r}
plot_months(totalRev_LM$residuals)
plot_months(totalRev_LM$residuals[1:72])
plot_months(totalRev_LM$residuals[228:300])
```

```{r}
stationary_test(totalRev_LM$residuals)
```

```{r}
sarima1 = arima(linear_residuals, order = c(1,0,0), seasonal = list(order = c(0,1,0)))
plot(sarima1)
stationary_test(sarima1$residuals)
```

```{r}
sarima2 = arima(linear_residuals, order = c(1,0,0), seasonal = list(order = c(0,1,1)))
plot(sarima2)
stationary_test(sarima2$residuals)
```

```{r}
sarima3 = arima(linear_residuals, order = c(1,0,0), seasonal = list(order = c(1,1,1)))
plot(sarima3)
stationary_test(sarima3$residuals)
```

```{r}
sarima4 = arima(linear_residuals, order = c(1,1,1), seasonal = list(order = c(1,1,1)))
plot(sarima4)
stationary_test(sarima4$residuals)
```

```{r}
residuals_diff11 = diff(diff(linear_residuals, k = 12), k = 1)
stationary_test(residuals_diff11)
qqnorm(residuals_diff11)
qqline(residuals_diff11)
```


```{r}
eacf(residuals_diff11, ar.max = 28, ma.max = 28)
```

Since the results display substantial seasonality, that's go back and fit a cosine trend to the data.

```{r}
time. = time(totalRev)
har. = harmonic(totalRev)
totalRev_CM1 = lm(totalRev ~ time. + har.)
summary(totalRev_CM1)
```

```{r}
time. = time(totalRev)
har. = harmonic(totalRev, m = 2)
totalRev_CM2 = lm(totalRev ~ time. + har.)
summary(totalRev_CM2)
```


```{r}
plot(totalRev_LM)
plot(totalRev_CM1)
plot(totalRev_CM2)
#stationary_test(totalRev_LM$residuals)
# stationary_test(totalRev_CM2$residuals)
```

```{r}
plot_months(totalRev_LM$residuals[1:36])
plot_months(totalRev_CM1$residuals[1:36])
plot_months(totalRev_CM2$residuals[1:36])
```

```{r}
sarima4 = arima(totalRev_CM2$residuals, order = c(0,1,2), seasonal = list(order = c(1,1,1)))
plot(sarima4)
stationary_test(sarima4$residuals)
```

```{r}
armasubsets(sarima4$residuals, nar=12, nma =12)
eacf(sarima4$residuals, ar.max = 13, ma.max = 13)
```

```{r}
x = totalRev_CM2$residuals
#print(runs(x))
print(runs(diff(x)))
#print(runs(diff(diff(x))))
print(runs(diff(diff(diff(x))), k = 12))
print(runs(diff(diff(x)), k = 12))
```

```{r}
sarima0 = arima(totalRev_LM$residuals, order = c(0,1,2), seasonal = list(order=c(0,1,1),period= 12))
hist(sarima0$residuals)
qqnorm(rstandard(sarima0))
qqline(rstandard(sarima0))
stationary_test(sarima0$residuals)
```

