---
title: "Data Exploration" 
output: html_document 
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=8, fig.height=5) 

library(ggplot2)
library(TSA)
library(readr)
```

## Importing/Processing Data

```{r}
data <- read_csv("sales_revenue_clean.csv")
```

```{r}
save_plot = function(series, name, months = FALSE, plt_width = 640){
  Month=c('J','F','M','A','M','J','J','A','S','O','N','D')
  
  path = paste('plots', name, sep = '/')
  png(paste(path, '.png', sep = ''), width = plt_width)
  
  plot(series)
  if (months){
    points(series,pch=Month)
  }
  dev.off()
}
```



```{r}
data$Tot_Sale
x = as.numeric(data$Tot_Sales)
# x
```



```{r}
# time = seq(as.Date("1990-01-01"), as.Date("2021-01-01"), by="months")
totalSales <- ts(data$Tot_Sales,start=c(1990,1),frequency=12)
totalRev <- ts(data$Tot_Revenue,start=c(1990,1),frequency=12)
totalPrice <- ts(data$Tot_Price,start=c(1990,1),frequency=12)


rSales <- ts(data$R_Sales,start=c(1990,1),frequency=12)
rRev <- ts(data$R_Revenue,start=c(1990,1),frequency=12)
rPrice <- ts(data$R_Price,start=c(1990,1),frequency=12)

cSales <- ts(data$C_Sales,start=c(1990,1),frequency=12)
cRev <- ts(data$C_Revenue,start=c(1990,1),frequency=12)
cPrice <- ts(data$C_Price,start=c(1990,1),frequency=12)

iSales <- ts(data$I_Sales,start=c(1990,1),frequency=12)
iRev <- ts(data$I_Revenue,start=c(1990,1),frequency=12)
iPrice <- ts(data$I_Price,start=c(1990,1),frequency=12)

tSales <- ts(data$T_Sales,start=c(1990,1),frequency=12)
tRev <- ts(data$T_Revenue,start=c(1990,1),frequency=12)
tPrice <- ts(data$T_Price,start=c(1990,1),frequency=12)

oSales <- ts(data$O_Sales,start=c(1990,1),frequency=12)
oRev <- ts(data$O_Revenue,start=c(1990,1),frequency=12)
oPrice <- ts(data$O_Price,start=c(1990,1),frequency=12)
```


## Initial Plot of Data

### Plots of Residential Data

```{r}

Month=c('J','F','M','A','M','J','J','A','S','O','N','D')

plot(rSales, main = "Residential Sales")
points(rSales,pch=Month)
```

```{r}
plot(rRev, main = "Residential Revenue")
points(rRev,pch=Month)
```

### Plots of Total Data

```{r}
Month=c('J','F','M','A','M','J','J','A','S','O','N','D')

plot(totalSales, main = "Total Sales")
points(totalSales,pch=Month)

plot(totalPrice, main = "Total Price")
points(totalPrice,pch=Month)

plot(totalRev, main = "Total Revenue")
points(totalRev,pch=Month)
```

```{r}
totalMA = filter(totalRev,rep(1,13)/13,sides=2) # 1 year MA
plot(cbind(totalMA),plot.type='single',col=4:1,lwd=2, ylab="flow", main = "Total MA" )
lines(totalSales)

rMA = filter(rRev,rep(1,13)/13,sides=2) # 1 year MA
plot(cbind(rMA),plot.type='single',col=4:1,lwd=2, ylab="flow", main = "Residential MA")
lines(rSales)

cMA = filter(cRev,rep(1,13)/13,sides=2) # 1 year MA
plot(cbind(cMA),plot.type='single',col=4:1,lwd=2, ylab="flow", main = "Construction MA")
lines(cSales)

iMA = filter(iRev,rep(1,13)/13,sides=2) # 1 year MA
plot(cbind(iMA),plot.type='single',col=4:1,lwd=2, ylab="flow", main = "Industrial MA")
lines(iSales)
```

```{r}
plot(cbind(totalMA/1e6,rMA/1e6,cMA/1e6, iMA/1e6),plot.type='single',col=4:1,lwd=2, ylab="sales (Millions of $)", main = "Electricity sales (12 month MA) by Sector")
legend(x = 'topleft', legend = c('Total', 'Residential', 'Commercial', 'Industrial'), col = 4:1, lwd = 2)
# green is residential
# red is c
# black is industrial
```

```{r}
acf(totalRev)
pacf(totalRev)
```


```{r}
# bc = BoxCox.ar(totalSales)
```
```{r}
# bc$mle
# bc$loglike
```

```{r}
# mle is -0.6
total_transformed = totalRev^(-0.6)
plot(total_transformed)
```

```{r}
Time = time(total_transformed)
totalRev_LM = lm(totalRev ~ Time)
summary(totalRev_LM)
```

```{r}
plot(totalRev_LM)
```

```{r}
plot(totalRev_LM$residuals)
plot(rstandard(totalRev_LM))
linear_residuals = rstandard(totalRev_LM)
plot(diff(rstandard(totalRev_LM), k = 12))
```


```{r}
acf(total_transformed)
pacf(total_transformed)
```

```{r}
acf(diff(total_transformed))
pacf(diff(total_transformed))
```

```{r}
acf(diff(diff(total_transformed), 12))
pacf(diff(diff(total_transformed), 12))
```

```{r}
eacf(diff(diff(total_transformed), 12))
armasubsets(diff(diff(total_transformed), 12), nar = 12, nma = 12)
```

```{r}
acf(linear_residuals)
pacf(linear_residuals)
```

```{r}
acf(diff(linear_residuals, 12))
pacf(diff(linear_residuals, 12))
eacf(diff(linear_residuals, 12))
```

```{r}
runs(diff(linear_residuals, 12))
shapiro.test(diff(linear_residuals, 12))
```

```{r}
sarima1 = arima(linear_residuals, order = c(1,0,0), seasonal = list(order = c(0,1,0)))
plot(sarima1)
```

```{r}
acf(sarima1$residuals)
pacf(sarima1$residuals)
```


```{r}
plot(sarima1$residuals)
runs(sarima1$residuals)
shapiro.test(sarima1$residuals)
```

